from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import JsonResponse
from django.urls import include, path

from articles.blueprints import (
    blueprint_detail_view,
    blueprint_list_view,
    blueprint_studio_view,
    bundle_detail_view,
    bundle_list_view,
    capability_detail_view,
    capability_list_view,
    context_pack_activate,
    context_pack_deactivate,
    context_pack_detail,
    list_context_packs,
    create_draft_session,
    enqueue_draft_generation,
    enqueue_draft_revision,
    enqueue_transcription,
    get_bundle,
    get_capability,
    get_draft_session,
    get_voice_note,
    internal_draft_session,
    internal_draft_session_context,
    internal_draft_session_error,
    internal_draft_session_status,
    internal_draft_session_update,
    internal_openai_config,
    internal_registry_sync,
    internal_registry_detail,
    internal_release_plan_generate,
    internal_release_plan_detail,
    internal_run_artifact,
    internal_run_update,
    internal_context_resolve,
    internal_registry_sync,
    internal_release_plan_generate,
    internal_run_artifact,
    internal_run_update,
    internal_voice_note,
    internal_voice_note_audio,
    internal_voice_note_error,
    internal_voice_note_status,
    internal_voice_note_transcript,
    list_bundles,
    list_capabilities,
    module_detail_view,
    module_list_view,
    new_draft_session_view,
    instantiate_blueprint,
    upload_voice_note,
)
from articles.provisioning_views import (
    bootstrap_log_view,
    destroy_instance_view,
    get_instance,
    list_instances,
)
from articles.public_views import public_article_detail, public_articles
from articles.xyn_api import (
    blueprints_collection,
    blueprint_detail,
    blueprint_runs,
    blueprint_submit,
    modules_collection,
    module_detail,
    registries_collection,
    registry_detail,
    registry_sync,
    release_plans_collection,
    release_plan_detail,
    release_plan_generate,
    runs_collection,
    run_detail,
    run_logs,
    run_artifacts,
)
from web.public_views import (
    public_home,
    public_menu,
    public_page_detail,
    public_page_sections,
    public_pages,
    public_site_config,
)
def healthcheck(_request):
    return JsonResponse(
        {"status": "ok", "admin": "/admin/", "articles": "/api/articles/"},
    )

urlpatterns = [
    path("", healthcheck),
    path("admin/", admin.site.urls),
    path("api/", include("articles.urls")),
    path("xyn/api/public/menu", public_menu),
    path("xyn/api/public/pages", public_pages),
    path("xyn/api/public/pages/<slug:slug>", public_page_detail),
    path("xyn/api/public/pages/<slug:slug>/sections", public_page_sections),
    path("xyn/api/public/home", public_home),
    path("xyn/api/public/site", public_site_config),
    path("xyn/api/public/articles", public_articles),
    path("xyn/api/public/articles/<slug:slug>", public_article_detail),
    path("xyn/blueprints/", blueprint_list_view, name="blueprint-list"),
    path("xyn/studio/blueprints/new", new_draft_session_view, name="blueprint-session-new"),
    path("xyn/blueprints/<uuid:blueprint_id>/", blueprint_detail_view, name="blueprint-detail"),
    path("xyn/modules/", module_list_view, name="module-list"),
    path("xyn/modules/<uuid:module_id>/", module_detail_view, name="module-detail"),
    path("xyn/bundles/", bundle_list_view, name="bundle-list"),
    path("xyn/bundles/<uuid:bundle_id>/", bundle_detail_view, name="bundle-detail"),
    path("xyn/capabilities/", capability_list_view, name="capability-list"),
    path("xyn/capabilities/<uuid:capability_id>/", capability_detail_view, name="capability-detail"),
    path("xyn/studio/blueprints/draft-sessions/<uuid:session_id>/", blueprint_studio_view, name="blueprint-studio"),
    path("xyn/api/blueprints", blueprints_collection),
    path("xyn/api/blueprints/<uuid:blueprint_id>", blueprint_detail),
    path("xyn/api/blueprints/<uuid:blueprint_id>/submit", blueprint_submit),
    path("xyn/api/blueprints/<uuid:blueprint_id>/runs", blueprint_runs),
    path("xyn/api/blueprints/<uuid:blueprint_id>/instantiate", instantiate_blueprint),
    path("xyn/api/modules", modules_collection),
    path("xyn/api/modules/<path:module_ref>", module_detail),
    path("xyn/api/bundles", list_bundles),
    path("xyn/api/bundles/<path:bundle_ref>", get_bundle),
    path("xyn/api/registries", registries_collection),
    path("xyn/api/registries/<uuid:registry_id>", registry_detail),
    path("xyn/api/registries/<uuid:registry_id>/sync", registry_sync),
    path("xyn/api/release-plans", release_plans_collection),
    path("xyn/api/release-plans/<uuid:plan_id>", release_plan_detail),
    path("xyn/api/release-plans/<uuid:plan_id>/generate", release_plan_generate),
    path("xyn/api/runs", runs_collection),
    path("xyn/api/runs/<uuid:run_id>", run_detail),
    path("xyn/api/runs/<uuid:run_id>/logs", run_logs),
    path("xyn/api/runs/<uuid:run_id>/artifacts", run_artifacts),
    path("xyn/api/capabilities", list_capabilities),
    path("xyn/api/capabilities/<path:capability_ref>", get_capability),
    path("xyn/api/context-packs", list_context_packs),
    path("xyn/api/context-packs/<uuid:pack_id>", context_pack_detail),
    path("xyn/api/context-packs/<uuid:pack_id>/activate", context_pack_activate),
    path("xyn/api/context-packs/<uuid:pack_id>/deactivate", context_pack_deactivate),
    path("xyn/api/voice-notes", upload_voice_note, name="voice-note-upload"),
    path("xyn/api/voice-notes/<uuid:voice_note_id>/enqueue-transcription", enqueue_transcription),
    path("xyn/api/voice-notes/<uuid:voice_note_id>", get_voice_note),
    path("xyn/api/draft-sessions", create_draft_session, name="draft-session-create"),
    path("xyn/api/draft-sessions/<uuid:session_id>/enqueue-draft-generation", enqueue_draft_generation),
    path("xyn/api/draft-sessions/<uuid:session_id>/enqueue-draft-revision", enqueue_draft_revision),
    path("xyn/api/draft-sessions/<uuid:session_id>", get_draft_session),
    path("xyn/api/provision/instances", list_instances),
    path("xyn/api/provision/instances/<uuid:instance_id>", get_instance),
    path("xyn/api/provision/instances/<uuid:instance_id>/destroy", destroy_instance_view),
    path("xyn/api/provision/instances/<uuid:instance_id>/bootstrap-log", bootstrap_log_view),
    path("xyn/internal/voice-notes/<uuid:voice_note_id>", internal_voice_note),
    path("xyn/internal/voice-notes/<uuid:voice_note_id>/audio", internal_voice_note_audio),
    path("xyn/internal/voice-notes/<uuid:voice_note_id>/transcript", internal_voice_note_transcript),
    path("xyn/internal/voice-notes/<uuid:voice_note_id>/error", internal_voice_note_error),
    path("xyn/internal/voice-notes/<uuid:voice_note_id>/status", internal_voice_note_status),
    path("xyn/internal/draft-sessions/<uuid:session_id>", internal_draft_session),
    path("xyn/internal/draft-sessions/<uuid:session_id>/context/resolve", internal_draft_session_context),
    path("xyn/internal/draft-sessions/<uuid:session_id>/draft", internal_draft_session_update),
    path("xyn/internal/draft-sessions/<uuid:session_id>/error", internal_draft_session_error),
    path("xyn/internal/draft-sessions/<uuid:session_id>/status", internal_draft_session_status),
    path("xyn/internal/openai-config", internal_openai_config),
    path("xyn/internal/context-packs/resolve", internal_context_resolve),
    path("xyn/internal/runs/<uuid:run_id>", internal_run_update),
    path("xyn/internal/runs/<uuid:run_id>/artifacts", internal_run_artifact),
    path("xyn/internal/registries/<uuid:registry_id>", internal_registry_detail),
    path("xyn/internal/registries/<uuid:registry_id>/sync", internal_registry_sync),
    path("xyn/internal/release-plans/<uuid:plan_id>", internal_release_plan_detail),
    path("xyn/internal/release-plans/<uuid:plan_id>/generate", internal_release_plan_generate),
    path("accounts/", include("allauth.urls")),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
